version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/mi-fastapi-app

permissions:
  - object: /home/ubuntu/mi-fastapi-app
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/install_python.sh
      timeout: 600
      runas: root  # Necesitas permisos de root para instalar Python

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
