version: 0.0  # Versión del formato de appspec
os: linux  # Sistema operativo de las instancias

# Archivos que se copiarán al servidor
files:
  - source: /  # Copia todos los archivos del proyecto
    destination: /home/ubuntu/mi-fastapi-app  # Directorio de destino en el servidor

# Permisos para los archivos copiados
permissions:
  - object: /home/ubuntu/mi-fastapi-app
    owner: ubuntu  # Dueño de los archivos
    group: ubuntu  # Grupo de los archivos
    mode: 755  # Permisos (rwxr-xr-x)

# Hooks: scripts que se ejecutan en diferentes etapas del despliegue
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh  # Detiene el servidor actual (si existe)
      timeout: 300  # Tiempo máximo de ejecución en segundos
      runas: ubuntu  # Usuario que ejecuta el script

  ApplicationStart:
    - location: scripts/start_server.sh  # Inicia el servidor FastAPI
      timeout: 300
      runas: ubuntu
